
name: Pack and publish extension

# Controls when the workflow will run
on:
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3.4.1
      
      - name: Prepublish
        run: npm run vscode:prepublish
      
      - name: npm install 
        run: npm install
      
      - name: Package extension
        run: npx vsce package --out vsix/
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: vsix/*.vsix
        


